[tool.cibuildwheel]
skip = "cp36-*" # scikit-build-core requires >=3.7
build-verbosity = 3

[tool.cibuildwheel.linux]
before-all = [
    "yum remove -y cmake",
    "yum install -y libX11-devel libXcursor-devel libXrandr-devel libXinerama-devel mesa-libGL-devel mesa-libGL libXi-devel freeglut-devel mesa-libEGL-devel"
]

# musllinux builds on an Alpinx Linux image, need different package names
[[tool.cibuildwheel.overrides]]
select = "*-musllinux*"
before-all = "apk add libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev freeglut-dev mesa-dev mesa-gl mesa-egl"